---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quay-mirror-config
  namespace: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "25"
data:
  mirror-config.yaml: |
    # Multi-cluster Quay Registry Mirroring Configuration
    mirrors:
      - name: quay-ocp-prd
        endpoint: https://quay.apps.ocp-prd.kohlerco.com
        username: mirror-service-account
        token_secret: quay-mirror-prd-token
        sync_interval: 3600  # 1 hour
        sync_retries: 3
        
      - name: quay-ocp-dr  
        endpoint: https://quay.apps.ocp-dr.kohlerco.com
        username: mirror-service-account
        token_secret: quay-mirror-dr-token
        sync_interval: 1800  # 30 minutes (DR needs faster sync)
        sync_retries: 5
        
      - name: quay-ocp4
        endpoint: https://quay.apps.ocp4.kohlerco.com
        username: mirror-service-account
        token_secret: quay-mirror-ocp4-token
        sync_interval: 7200  # 2 hours (legacy cluster)
        sync_retries: 3
        
    # Repository mirror rules
    repository_mirrors:
      - source_repo: "kohler/*"
        target_clusters: ["ocp-prd", "ocp-dr"]
        sync_tags: ["latest", "stable", "v*"]
        
      - source_repo: "platform/*"
        target_clusters: ["ocp-prd", "ocp-dr", "ocp4"]
        sync_tags: ["*"]
        
      - source_repo: "security/*"
        target_clusters: ["ocp-prd", "ocp-dr"]
        sync_tags: ["latest", "stable"]
        
    # Sync policies
    sync_policies:
      - name: critical-apps
        repos: ["platform/balance-fit", "platform/hr-apps"]
        sync_interval: 900  # 15 minutes
        priority: high
        
      - name: dev-images
        repos: ["dev/*", "test/*"]
        sync_interval: 3600  # 1 hour
        priority: normal
