---
# Subscription for Group Sync Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: group-sync-operator
  namespace: group-sync-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/name: group-sync-operator
    app.kubernetes.io/part-of: group-sync-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: group-sync-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: group-sync-operator.v0.0.36
