apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mtc-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/kohler-openshift/kohler-openshift.git
    targetRevision: HEAD
    path: components/mtc-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-migration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
