apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mtc-operator
  namespace: openshift-migration

resources:
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml
  - migration-cluster-source.yaml
  - migration-cluster.yaml
  - migration-storage.yaml
  - ocp-prd-source-secret.yaml
  - ocp2-target-secret.yaml

commonLabels:
  app.kubernetes.io/name: mtc-operator
  app.kubernetes.io/part-of: migration-toolkit
  app.kubernetes.io/component: operator
