apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: migration-operator-group
  namespace: openshift-migration
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetNamespaces:
  - openshift-migration
