apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mtc-operator
  namespace: openshift-migration
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  channel: stable-1.12
  installPlanApproval: Automatic
  name: mtc-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
