apiVersion: v1
kind: Secret
metadata:
  name: vault-tls
  namespace: vault
type: kubernetes.io/tls
stringData:
  tls.crt: |
    # TODO: provide or manage via cert-manager on the Route; otherwise remove this file
  tls.key: |
    # TODO


