---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app: vault
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
        app.kubernetes.io/name: vault
        app.kubernetes.io/part-of: vault
    spec:
      serviceAccountName: vault
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000780000
        runAsGroup: 1000780000
        fsGroup: 1000780000
      initContainers:
      - name: vault-init
        image: busybox:1.35
        command: ["/bin/sh"]
        args:
        - -c
        - |
          mkdir -p /vault/logs
          chown -R 1000780000:1000780000 /vault/logs
          chmod -R 755 /vault/logs
        volumeMounts:
        - name: vault-logs
          mountPath: /vault/logs
        securityContext:
          runAsUser: 1000780000
          runAsGroup: 1000780000
      containers:
      - name: vault
        image: hashicorp/vault:1.15.2
        args:
        - "server"
        - "-config=/vault/config/vault.json"
        ports:
        - containerPort: 8200
          name: http
        - containerPort: 8201
          name: https-internal
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
          readOnly: true
        - name: vault-data
          mountPath: /vault/data
        - name: vault-logs
          mountPath: /vault/logs
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-data
        persistentVolumeClaim:
          claimName: vault-data
      - name: vault-logs
        emptyDir: {}
