---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
namespace: vault-secrets-system
resources:
  - ./namespace.yaml
  - ./operator-group.yaml
  - ./subscription.yaml
  - ./secret-store.yaml
