---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
  - vault-secrets-system
