---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: vault-secrets-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
