---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  # High Availability Configuration
  ha:
    enabled: true
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
  
  # Application Controller Configuration
  controller:
    processors: {}
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
    sharding:
      enabled: false
  
  # Dex Configuration (OIDC)
  dex:
    openShiftOAuth: true
    resources:
      requests:
        cpu: 250m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  
  # Redis Configuration
  redis:
    resources:
      requests:
        cpu: 250m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  
  # Repository Server Configuration
  repo:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    mountsatoken: true
  
  # Server Configuration
  server:
    # Enable gRPC-Web for better performance
    grpc:
      web: true
    
    # Route configuration
    route:
      enabled: true
      tls:
        termination: reencrypt
        insecureEdgeTerminationPolicy: Redirect
    
    # Resources
    resources:
      requests:
        cpu: 125m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    
    # RBAC Configuration
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        p, role:admin, applications, *, */*, allow
        p, role:admin, clusters, *, *, allow
        p, role:admin, repositories, *, *, allow
        p, role:admin, certificates, *, *, allow
        p, role:admin, accounts, *, *, allow
        p, role:admin, gpgkeys, *, *, allow
        p, role:admin, logs, *, *, allow
        p, role:admin, exec, *, *, allow
        g, system:cluster-admins, role:admin
        g, cluster-admins, role:admin
    
    # Configuration Management
    config:
      url: https://openshift-gitops-server-openshift-gitops.apps.ocp-dev.kohlerco.com
      application.instanceLabelKey: argocd.argoproj.io/instance
      
      # Git repositories configuration
      repositories: |
        - type: git
          url: https://github.com/rich-p-ai/kohler-openshift.git
          name: kohler-openshift
        
      # Resource exclusions (ignore certain resource types)
      resource.exclusions: |
        - apiGroups:
          - cilium.io
          kinds:
          - CiliumIdentity
          clusters:
          - "*"
        
      # Resource inclusions (ensure certain resources are managed)
      resource.inclusions: |
        - apiGroups:
          - config.openshift.io
          kinds:
          - "*"
          clusters:
          - "*"
      
      # Sync options
      resource.customizations.health.argoproj.io_Application: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
  
  # SSO Configuration (OpenShift OAuth)
  sso:
    provider: dex
    dex:
      openShiftOAuth: true
      
  # Initial Admin Password (will be auto-generated)
  extraConfig:
    accounts.admin: apiKey, login
    accounts.admin.enabled: "true"
