---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
namespace: openshift-gitops
resources:
  - ./rbac-configuration.yaml
  - ./argocd-cluster.yaml
