# OCP-DR Cluster Configuration
# Critical Infrastructure Components for DR Environment

default:
  project:
    name: cluster-config
    description: Project for DR cluster configuration
    namespace: cluster-config
    sourceRepos:
    - "{{ .Values.default.app.source.repoURL }}"
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  app:
    enabled: true
    enableAutoSync: true
    autoSyncPrune: false
    project: cluster-config
    labels:
      app-source: cluster-config
      repo: kohler-openshift
      cluster: ocp2
    destination:
      namespace: cluster-config
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/rich-p-ai/kohler-openshift.git
      targetRevision: HEAD
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true  
    - FailOnSharedResource=true
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
    syncPolicyRetry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

# Critical Infrastructure Applications
applications:
  # Phase 1: Core Infrastructure (Sync Wave 1-10)
   
  # network-configuration:
  #   enabled: true
  #   labels:
  #     component: infrastructure
  #     phase: core
  #   source:
  #     path: components/network-configuration
    
      
  # image-registry-configuration:
  #   enabled: true
  #   labels:
  #     component: infrastructure
  #     phase: core
  #   source:
  #     path: components/image-registry-configuration
  #   destination:
  #     namespace: openshift-image-registry
  #   syncOptions:
  #   - CreateNamespace=true

  # Phase 2: Storage and Data Protection (Sync Wave 5-25)
  odf-operator:
    enabled: true
    labels:
      component: storage
      phase: data
    source:
      path: components/odf-operator
    destination:
      namespace: openshift-storage
    syncOptions:
    - CreateNamespace=true
    
  odf-configuration:
    enabled: true
    labels:
      component: storage
      phase: data
    source:
      path: components/odf-configuration
    destination:
      namespace: openshift-storage

  # oadp-operator:
  #   enabled: true
  #   labels:
  #     component: backup
  #     phase: data
  #   source:
  #     path: components/oadp-operator
  #   destination:
  #     namespace: openshift-adp
  #   syncOptions:
  #   - CreateNamespace=true
    
  # oadp-configuration:
  #   enabled: true
  #   labels:
  #     component: backup
  #     phase: data
  #   source:
  #     path: components/oadp-configuration
  #   destination:
  #     namespace: openshift-adp
      
  # oadp-scheduled-backups:
  #   enabled: true
  #   labels:
  #     component: backup
  #     phase: data
  #   source:
  #     path: components/oadp-scheduled-backups
  #   destination:
  #     namespace: openshift-adp

  # Phase 3: Authentication and Security (Sync Wave 10)
  oauth-configuration:
    enabled: true
    labels:
      component: authentication
      phase: security
    source:
      path: components/oauth-configuration
    destination:
      namespace: openshift-config

  # Phase 4: Additional Operators (Sync Wave 5)
  # cert-manager-operator:
  #   enabled: true
  #   labels:
  #     component: security
  #     phase: operators
  #   source:
  #     path: components/cert-manager-operator
  #   destination:
  #     namespace: cert-manager-operator
  #   syncOptions:
  #   - CreateNamespace=true
    
  # Phase 5: Platform Integration (Sync Wave 4-6)
  odf-infrastructure:
    enabled: true
    labels:
      component: infrastructure
      phase: platform
    source:
      path: components/odf-infrastructure
    destination:
      namespace: openshift-machine-api
      
  # rbac-configuration:
  #   enabled: true
  #   labels:
  #     component: security
  #     phase: platform
  #   source:
  #     path: components/rbac-configuration
      
  # vsphere-configuration:
  #   enabled: true
  #   labels:
  #     component: platform
  #     phase: platform
  #   source:
  #     path: components/vsphere-configuration
      
  # security-policies:
  #   enabled: true
  #   labels:
  #     component: security
  #     phase: platform
  #   source:
  #     path: components/security-policies

  # Phase 6: Optional Advanced Components (Disabled by default for dev)
  # acm-operator:
  #   enabled: false  # Advanced Cluster Management - enable if needed
  #   labels:
  #     component: management
  #     phase: advanced
  #   source:
  #     path: components/acm-operator
  #   destination:
  #     namespace: open-cluster-management
  #   syncOptions:
  #   - CreateNamespace=true
    
  # acm-configuration:
  #   enabled: false  # ACM configuration - enable if needed
  #   labels:
  #     component: management
  #     phase: advanced
  #   source:
  #     path: components/acm-configuration
  #   destination:
  #     namespace: open-cluster-management
      
  # vault-deployment:
  #   enabled: true
  #   labels:
  #     component: security
  #     phase: advanced
  #   source:
  #     path: components/vault-deployment
  #   destination:
  #     namespace: vault-system
  #   syncOptions:
  #   - CreateNamespace=true

  # vault-rbac:
  #   enabled: true
  #   labels:
  #     component: security
  #     phase: advanced
  #   source:
  #     path: components/vault-rbac
  #   syncOptions:
  #   - CreateNamespace=true
    
  # vault-secrets-operator:
  #   enabled: true
  #   labels:
  #     component: security
  #     phase: advanced
  #   source:
  #     path: components/vault-secrets-operator
  #   destination:
  #     namespace: vault-secrets-system
  #   syncOptions:
  #   - CreateNamespace=true
    
  # vault-configuration:
  #   enabled: true
  #   labels:
  #     component: security
  #     phase: advanced
  #   source:
  #     path: components/vault-configuration
  #   destination:
  #     namespace: vault-secrets-system
  #   syncOptions:
  #   - CreateNamespace=true
    
  group-sync-operator:
    enabled: true
    labels:
      component: authentication
      phase: advanced
    source:
      path: components/group-sync-operator
    destination:
      namespace: group-sync-operator
    syncOptions:
    - CreateNamespace=true
    
  vault:
    enabled: true
    labels:
      component: security
      phase: platform
    source:
      path: components/vault
    destination:
      namespace: vault
    syncOptions:
    - CreateNamespace=true
    
  external-secrets:
    enabled: true
    labels:
      component: security
      phase: platform
    source:
      path: components/external-secrets-helm
    destination:
      namespace: external-secrets-system
    syncOptions:
    - CreateNamespace=true
  # kube-ops-view:
  #   enabled: false  # Cluster visualization - enable if needed
  #   labels:
  #     component: monitoring
  #     phase: advanced
  #   source:
  #     path: components/kube-ops-view
  #   destination:
  #     namespace: kube-ops-view
  #   syncOptions:
  #   - CreateNamespace=true

# Project Configuration
projects:
  cluster-config:
    annotations:
      notifications.argoproj.io/subscribe.on-sync-failed.slack: cluster-gitops
      notifications.argoproj.io/subscribe.on-health-degraded.slack: cluster-gitops
    description: "Core cluster infrastructure configuration for OCP-DR"
    namespace: cluster-config
    sourceRepos:
    - "{{ .Values.default.app.source.repoURL }}"
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
