---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    component: infrastructure
    phase: platform
    purpose: quay-infrastructure
    app.kubernetes.io/name: quay-infrastructure

resources:
  - ./quay-infra-machineset.yaml

commonLabels:
  app.kubernetes.io/name: quay-infrastructure
  app.kubernetes.io/component: registry-nodes


