apiVersion: v1
kind: Namespace
metadata:
  name: nodeport-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-test
  namespace: nodeport-test
  labels:
    app: nodeport-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeport-test
  template:
    metadata:
      labels:
        app: nodeport-test
    spec:
      containers:
        - name: hello-openshift
          image: quay.io/openshift/origin-hello-openshift:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10


