apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oadp-backup-credentials
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: cloud-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "15"
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .aws_access_key_id }}
          aws_secret_access_key={{ .aws_secret_access_key }}
  data:
  - secretKey: aws_access_key_id
    remoteRef:
      key: openshift/${ENVIRONMENT}/oadp  # Environment will be replaced by Kustomize
      property: aws_access_key_id
  - secretKey: aws_secret_access_key
    remoteRef:
      key: openshift/${ENVIRONMENT}/oadp
      property: aws_secret_access_key
