apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-credentials
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: registry-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "10"
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "quay.io": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
  - secretKey: username
    remoteRef:
      key: openshift/${ENVIRONMENT}/registry  # Environment will be replaced by Kustomize
      property: username
  - secretKey: password
    remoteRef:
      key: openshift/${ENVIRONMENT}/registry
      property: password
