apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vault
  namespace: vault

resources:
  - namespace.yaml
  - vault-deployment.yaml
  - vault-service.yaml
  - vault-configmap.yaml
  - vault-rbac.yaml
  - vault-route.yaml
  # vault-root-token-secret.yaml - Removed to prevent overwriting with placeholder
  - vault-azure-config-secret.yaml
  - vault-config-job.yaml
  # Simple Vault deployment for Azure AD testing
  - vault-simple-configmap.yaml
  - vault-simple-deployment.yaml
  - vault-simple-pvcs.yaml
  - vault-simple-service.yaml
  - vault-simple-route.yaml
  - vault-simple-config-job.yaml
  - vault-oidc-config-job.yaml

commonLabels:
  app.kubernetes.io/name: vault
  app.kubernetes.io/instance: vault
  app.kubernetes.io/part-of: platform

namespace: vault
