apiVersion: v1
kind: Secret
metadata:
  name: vault-azure-config
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: platform
type: Opaque
stringData:
  tenant-id: "REPLACE_WITH_AZURE_TENANT_ID"
  service-principal-id: "REPLACE_WITH_AZURE_SERVICE_PRINCIPAL_ID"
  # Note: You'll need to replace these values with your actual Azure AD configuration
  # To get these values, you'll need to:
  # 1. Create an Azure AD App Registration
  # 2. Get the Tenant ID from Azure AD
  # 3. Create a Service Principal and get its ID
