apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-simple
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-simple
    app.kubernetes.io/part-of: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-simple
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-simple
    spec:
      serviceAccountName: vault
      containers:
      - name: vault
        image: hashicorp/vault:1.15.2
        command: ["vault"]
        args: ["server", "-config=/vault/config/vault.json"]
        ports:
        - containerPort: 8200
          name: http
        - containerPort: 8201
          name: https-internal
        env:
        - name: VAULT_DISABLE_MLOCK
          value: "true"
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
          readOnly: true
        - name: vault-data
          mountPath: /vault/file
        - name: vault-logs
          mountPath: /vault/logs
        livenessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
            port: 8200
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
            port: 8200
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 2Gi
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
      volumes:
      - name: vault-config
        configMap:
          name: vault-simple-config
      - name: vault-data
        persistentVolumeClaim:
          claimName: vault-simple-data
      - name: vault-logs
        persistentVolumeClaim:
          claimName: vault-simple-logs
      securityContext:
        fsGroup: 1000810000
