apiVersion: v1
kind: Secret
metadata:
  name: vault-root-token
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: platform
type: Opaque
stringData:
  token: "REPLACE_WITH_ACTUAL_VAULT_ROOT_TOKEN"
