---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
namespace: vault-secrets-system
resources:
  - ./vault-auth.yaml
  - ./vault-static-secret.yaml
  - ./vault-connection.yaml
