---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "9"
resources:
  - ./network-policies.yaml
  - ./pod-security-policies.yaml
