---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
namespace: openshift-config
resources:
  - ./vault-auth.yaml
  - ./vault-connection.yaml
  - ./vault-static-secret.yaml
  - ./oauth-cluster-config.yaml
  - ./group-mapping.yaml
