---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  identityProviders:
  - mappingMethod: claim
    name: azureadsso
    openID:
      claims:
        email:
        - email
        name:
        - name
        preferredUsername:
        - upn
        groups:
        - groups
      clientID: 8bc87509-6d01-4739-b120-e84019342d66
      clientSecret:
        name: openid-client-secret-azuread
      extraScopes:
      - groups
      issuer: https://login.microsoftonline.com/5d2d3f03-286e-4643-8f5b-10565608e5f8
    type: OpenID
