---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault-system
data:
  vault.hcl: |
    ui = true
    
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
      tls_key_file = "/vault/userconfig/vault-server-tls/tls.key"
    }

    storage "file" {
      path = "/vault/data"
    }

    # API address for cluster communication
    api_addr = "https://vault.${CLUSTER_BASE_DOMAIN}:8200"
    cluster_addr = "https://vault.vault-system.svc.cluster.local:8201"

    # Disable mlock for containerized environments
    disable_mlock = true

    # Log level
    log_level = "INFO"

    # Telemetry
    telemetry {
      prometheus_retention_time = "30s"
      disable_hostname = true
    }
