---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "15"
namespace: openshift-storage
resources:
  - ./storage-system.yaml
  - ./storage-cluster.yaml
