---
# ODF Resource Profile Fix - Revert from lean to balanced
# This patch fixes the critical Ceph monitor quorum issue caused by insufficient resources and scheduling conflicts

apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: Replace
spec:
  resourceProfile: balanced
  # Fix node placement and tolerations for monitor scheduling
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cluster.ocs.openshift.io/openshift-storage
              operator: Exists
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
    mon:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cluster.ocs.openshift.io/openshift-storage
              operator: Exists
            - key: node-role.kubernetes.io/infra
              operator: Exists
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
  resources:
    mgr:
      limits:
        cpu: "3"
        memory: 6Gi
      requests:
        cpu: "2"
        memory: 4Gi
    mon:
      limits:
        cpu: "3"
        memory: 4Gi
      requests:
        cpu: "2"
        memory: 2Gi
    osd:
      limits:
        cpu: "3"
        memory: 6Gi
      requests:
        cpu: "2"
        memory: 4Gi
    mds:
      limits:
        cpu: "3"
        memory: 12Gi
      requests:
        cpu: "2"
        memory: 8Gi
