---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "8"
resources:
  - ./registry-storage.yaml
  - ./registry-config.yaml
