apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: external-secrets-system

# Use Helm to deploy External Secrets Operator
helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.9.9
  releaseName: external-secrets
  namespace: external-secrets-system
  valuesInline:
    installCRDs: true

# Additional resources
resources:
- namespace.yaml

commonLabels:
  app.kubernetes.io/name: external-secrets
  app.kubernetes.io/part-of: platform
  component: security

namespace: external-secrets-system
