apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: external-secrets-system

# Additional resources
resources:
- namespace.yaml

commonLabels:
  app.kubernetes.io/name: external-secrets
  app.kubernetes.io/part-of: platform
  component: security

namespace: external-secrets-system
