---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: platform
    component: security
  annotations:
    argocd.argoproj.io/sync-wave: "0"
