apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-k8s-auth
  namespace: external-secrets-system
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-operator"
          serviceAccountRef:
            name: "external-secrets"
