---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quay-postgres
  namespace: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  serviceName: quay-postgres-service
  replicas: 3
  selector:
    matchLabels:
      app: quay-postgres
  template:
    metadata:
      labels:
        app: quay-postgres
    spec:
      # Node selector to target Quay infrastructure nodes
      nodeSelector:
        node-role.kubernetes.io/quay: ""
      # Tolerations for infrastructure taints
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule
      containers:
        - name: postgres
          image: registry.redhat.io/rhel8/postgresql-13:latest
          env:
            - name: POSTGRESQL_DATABASE
              value: "quay"
            - name: POSTGRESQL_USER
              value: "quayuser"
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quay-postgres-credentials
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/pgsql/data
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - --live
            initialDelaySeconds: 120
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ocs-storagecluster-ceph-rbd
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: quay-postgres-service
  namespace: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  selector:
    app: quay-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
