---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "15"
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id=jqNj4v6H0CNdJfwFrrIa
    aws_secret_access_key=SNNGRb6aNvSh2MBdRn9Li/E7uLbko8Vef64FyRTu
