---
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: ocp2-velero-config
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  configuration:
    velero:
      defaultPlugins:
      - openshift
      - aws
      - csi
      featureFlags:
      - EnableCSI
    nodeAgent:
      enable: true
      uploaderType: restic
  backupLocations:
  - velero:
      config:
        region: us-east-1
        s3ForcePathStyle: "true"
        s3Url: https://s3-openshift-storage.apps.ocp-host.kohlerco.com
        insecureSkipTLSVerify: "true"
      credential:
        key: cloud
        name: cloud-credentials
      default: true
      objectStorage:
        bucket: kohler-oadp-backups-ec378362-ab9d-433a-bd1a-87af6e630eba
        prefix: ocp2
      provider: aws
    name: ocp2-backup-location
  snapshotLocations:
  - velero:
      config:
        region: us-east-1
      provider: aws
    name: ocp2-snapshot-location
